function pageHead(title,desc){return `<div class="page-head"><div><h2 class="page-title">${title}</h2><p class="page-desc">${desc}</p></div><span class="demo">Personal tracker</span></div>`}

function statusBreakdown(){
  const order=['Prepared','Applied','Under review','Interview completed','No outcome found','Talent pool / EOI','CV acknowledged','Rejected','Role withdrawn','Recruitment cancelled','Ad closed'],map={};
  state.rows.forEach(r=>map[r.Status]=(map[r.Status]||0)+1);
  const total=state.rows.length||1,colors={'Prepared':'var(--prepared)','Applied':'var(--accent)','Under review':'var(--accent)','Interview completed':'var(--good)','No outcome found':'var(--warn)','Talent pool / EOI':'var(--good)','CV acknowledged':'var(--good)','Rejected':'var(--risk)','Role withdrawn':'var(--ink-3)','Recruitment cancelled':'var(--ink-3)','Ad closed':'var(--ink-3)'};
  return `<div class="status-strip">${order.filter(s=>map[s]).map(s=>`<div class="status-seg" title="${esc(s)}: ${map[s]}" style="width:${map[s]/total*100}%;background:${colors[s]}"></div>`).join('')}</div><div class="legend">${order.filter(s=>map[s]).map(s=>`<span><i style="background:${colors[s]}"></i>${esc(shortStatus(s))} ${map[s]}</span>`).join('')}</div>`;
}

function weeklySeries(){const m=new Map();state.rows.forEach(r=>{const d=dateFrom(r['Applied date']);if(!d)return;const x=new Date(d),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);const k=x.toISOString().slice(0,10);m.set(k,(m.get(k)||0)+1)});return [...m.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-12)}
function lineChart(series){if(!series.length)return `<div class="empty">No dated applications yet.</div>`;const W=650,H=220,pL=32,pR=12,pT=15,pB=30,max=Math.max(1,...series.map(x=>x[1])),pts=series.map((x,i)=>[pL+i/(Math.max(1,series.length-1))*(W-pL-pR),H-pB-(x[1]/max)*(H-pT-pB)]),path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '),area=path+` L ${pts[pts.length-1][0]} ${H-pB} L ${pts[0][0]} ${H-pB} Z`;return `<svg class="svg-chart" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${[0,.25,.5,.75,1].map(t=>{const y=pT+t*(H-pT-pB);return`<line class="gridline" x1="${pL}" y1="${y}" x2="${W-pR}" y2="${y}"/>`}).join('')}<path class="chart-fill" d="${area}"/><path class="chart-line" d="${path}"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="3.5" fill="var(--surface)" stroke="var(--accent)" stroke-width="2"><title>${series[i][0]}: ${series[i][1]}</title></circle>`).join('')}${series.map((x,i)=>i%Math.max(1,Math.ceil(series.length/6))===0?`<text class="axis" x="${pts[i][0]}" y="${H-8}" text-anchor="middle">${x[0].slice(5)}</text>`:'').join('')}</svg>`}

function deadlineRows(limit=8){return state.rows.filter(r=>r.Status==='Prepared').sort((a,b)=>(dateFrom(a.Deadline)||new Date(8640000000000000))-(dateFrom(b.Deadline)||new Date(8640000000000000))).slice(0,limit)}
function deadlineMarkup(r){const n=daysUntil(r.Deadline),missing=n===null,label=missing?'—':n<0?`${Math.abs(n)}d late`:n===0?'Today':`${n}d`;return `<div class="deadline-row"><div class="days">${label}<span>${missing?'No date':'remaining'}</span></div><div class="deadline-main"><strong>${esc(r.Company)} · ${esc(r.Role)}</strong><p>${statusBadge(r.Status)}${r['Job ID']?` · ${esc(r['Job ID'])}`:''}</p></div><div class="deadline-date">${r.Deadline?esc(fmtDate(r.Deadline)):'No deadline'}</div>${linkFor(r,'Apply link')?`<a class="mini-link" href="${esc(linkFor(r,'Apply link'))}" target="_blank" rel="noopener">Apply</a>`:`<span class="badge b-neutral">No link</span>`}</div>`}
function attentionItems(){const out=[];state.rows.forEach(r=>{if(r.Status==='Prepared'){const n=daysUntil(r.Deadline);if(n===null)out.push(['Missing deadline',r]);else if(n<0)out.push(['Prepared but expired',r]);else if(n<=3)out.push(['Deadline imminent',r]);if(!linkFor(r,'Apply link'))out.push(['Missing apply link',r])}if(r.Status==='No outcome found'){const d=dateFrom(r['Applied date']);if(d&&(Date.now()-d)>30*86400000)out.push(['No outcome >30 days',r])}});return out.slice(0,8)}

function overview(){
  const c=counts(),dated=state.rows.filter(r=>r['Applied date']).length,awaiting=state.rows.filter(r=>['Applied','Under review','No outcome found'].includes(r.Status)).length,att=attentionItems();
  return `${pageHead('Overview','The application pipeline, immediate deadlines and the records that need attention.')}<section class="grid kpis"><div class="card"><div class="eyebrow">Tracked</div><div class="kpi-value">${c.total}</div><div class="kpi-sub">All application records</div></div><div class="card"><div class="eyebrow">Prepared</div><div class="kpi-value">${c.prepared}</div><div class="kpi-sub">Ready to submit</div></div><div class="card"><div class="eyebrow">Awaiting</div><div class="kpi-value">${awaiting}</div><div class="kpi-sub">Submitted without a closed outcome</div></div><div class="card"><div class="eyebrow">Interviews</div><div class="kpi-value">${c.interviews}</div><div class="kpi-sub">Interview completions recorded</div></div><div class="card"><div class="eyebrow">Dated submissions</div><div class="kpi-value">${dated}</div><div class="kpi-sub">Rows with an applied date</div></div></section><section class="grid two"><div class="card"><div class="section-title"><div><h3>Application activity</h3><p>Submissions by week.</p></div></div>${lineChart(weeklySeries())}</div><div class="card"><div class="section-title"><div><h3>Status distribution</h3><p>Current status mix.</p></div></div>${statusBreakdown()}<div style="margin-top:18px" class="section-title"><div><h3>Attention</h3><p>Deadline, ageing and link checks.</p></div></div>${att.length?att.map(([t,r])=>`<div class="attention-row" data-open="${r._row}"><div><strong>${esc(t)}</strong><div class="small">${esc(r.Company)} · ${esc(r.Role)}</div></div><span class="row-chevron">›</span></div>`).join(''):`<div class="notice">Nothing needs immediate attention.</div>`}</div></section><section class="card" style="margin-top:11px"><div class="section-title"><div><h3>Next prepared applications</h3><p>Sorted by deadline. Missing dates stay visible.</p></div><button class="btn" data-goto="deadlines">View all</button></div><div class="deadline-list">${deadlineRows().map(deadlineMarkup).join('')||'<div class="empty">No prepared applications in this workbook.</div>'}</div></section>`;
}

function laneRows(type){if(type==='prepared')return state.rows.filter(r=>r.Status==='Prepared');if(type==='submitted')return state.rows.filter(r=>['Applied','Under review','No outcome found','CV acknowledged','Talent pool / EOI'].includes(r.Status));if(type==='interview')return state.rows.filter(r=>r.Status==='Interview completed');return state.rows.filter(r=>CLOSED.has(r.Status))}
function cardMarkup(r){const n=daysUntil(r.Deadline);return `<div class="job-card" data-open="${r._row}"><div class="co">${esc(r.Company)}</div><div class="rl">${esc(r.Role)}</div><div class="meta"><span>${statusBadge(r.Status)}</span><span>${r.Deadline?(n===null?'':n<0?'Expired':n===0?'Due today':`${n}d`):r['Applied date']?fmtDate(r['Applied date']):''}</span></div></div>`}
function pipeline(){const lanes=[['prepared','Prepared'],['submitted','Submitted / awaiting'],['interview','Interview'],['closed','Closed']];return `${pageHead('Pipeline','Scan the current workflow by stage. Click a card for details and links.')}<div class="toolbar"><input class="search" id="pipeSearch" placeholder="Filter pipeline" value="${esc(state.filter)}"><label class="check"><input type="checkbox" id="pipeHide" ${state.hideClosed?'checked':''}> Hide closed</label></div><div class="kanban">${lanes.filter(x=>!(state.hideClosed&&x[0]==='closed')).map(([k,t])=>{let rows=laneRows(k),q=keyNorm(state.filter);if(q)rows=rows.filter(r=>keyNorm([r.Company,r.Role,r.Status].join(' ')).includes(q));return`<div class="lane"><div class="lane-head"><strong>${t}</strong><span>${rows.length}</span></div>${rows.length?rows.map(cardMarkup).join(''):`<div class="empty">No ${t.toLowerCase()} records.</div>`}</div>`}).join('')}</div>`}

function toolbar(){const statuses=['All',...new Set(state.rows.map(r=>r.Status).filter(Boolean))];return `<div class="toolbar"><input class="search" id="appSearch" placeholder="Search company, role, ID, contact or notes" value="${esc(state.filter)}"><select class="select" id="statusFilter">${statuses.map(s=>`<option ${state.status===s?'selected':''}>${esc(s)}</option>`).join('')}</select><select class="select" id="companyFilter"><option>All</option>${companies().map(c=>`<option ${state.company===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select class="select" id="sortFilter"><option value="recent" ${state.sort==='recent'?'selected':''}>Recent activity</option><option value="deadline" ${state.sort==='deadline'?'selected':''}>Deadline</option><option value="company" ${state.sort==='company'?'selected':''}>Company</option></select><label class="check"><input type="checkbox" id="hideClosed" ${state.hideClosed?'checked':''}> Hide closed</label><button class="btn" id="csvBtn">Export CSV</button></div>`}
function appTable(){const rows=filteredRows();return `${toolbar()}<div class="table-wrap"><table><thead><tr><th>Status</th><th>Company</th><th>Role</th><th>Applied</th><th>Deadline</th><th>Job ID</th><th>Contact</th><th>Links</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr data-open="${r._row}"><td>${statusBadge(r.Status)}</td><td class="company">${esc(r.Company)}</td><td class="role">${esc(r.Role)}</td><td>${esc(fmtDate(r['Applied date']))}</td><td>${esc(fmtDate(r.Deadline))}</td><td>${esc(r['Job ID']||'')}</td><td>${esc(r.Contact||'')}</td><td><div class="linkrow">${usefulLinks(r).slice(0,5).map(([l,u])=>`<a class="mini-link" href="${esc(u)}" target="_blank" rel="noopener" onclick="event.stopPropagation()">${esc(l)}</a>`).join('')}</div></td><td class="row-chevron">›</td></tr>`).join('')}</tbody></table>${rows.length?'':'<div class="empty">No applications match these filters.</div>'}</div><div class="footer-note">Showing ${rows.length} of ${state.rows.length} records.</div>`}
function applications(){return `${pageHead('Applications','Search, filter and open the full register. Closed applications are hidden by default.')}${appTable()}`}

function deadlines(){const prep=state.rows.filter(r=>r.Status==='Prepared').sort((a,b)=>(dateFrom(a.Deadline)||new Date(8640000000000000))-(dateFrom(b.Deadline)||new Date(8640000000000000))),dated=prep.filter(r=>dateFrom(r.Deadline)),missing=prep.filter(r=>!dateFrom(r.Deadline));return `${pageHead('Deadlines','Prepared applications prioritised by closing date.')}<section class="grid kpis" style="grid-template-columns:repeat(3,1fr)"><div class="card"><div class="eyebrow">Prepared</div><div class="kpi-value">${prep.length}</div><div class="kpi-sub">Ready to submit</div></div><div class="card"><div class="eyebrow">Due within 7 days</div><div class="kpi-value">${dated.filter(r=>{const n=daysUntil(r.Deadline);return n!==null&&n>=0&&n<=7}).length}</div><div class="kpi-sub">Prioritise first</div></div><div class="card"><div class="eyebrow">Deadline missing</div><div class="kpi-value">${missing.length}</div><div class="kpi-sub">No date in the workbook</div></div></section><div class="card"><div class="section-title"><div><h3>Submission queue</h3><p>Countdowns use your local date.</p></div></div><div class="deadline-list">${prep.map(deadlineMarkup).join('')||'<div class="empty">No prepared applications in this workbook.</div>'}</div></div>`}

function bars(entries){const max=Math.max(1,...entries.map(x=>x[1]));return `<div class="bar-list">${entries.map(([k,v])=>`<div class="bar-row"><label title="${esc(k)}">${esc(shortStatus(k))}</label><div class="track"><div class="fill" style="width:${v/max*100}%"></div></div><span class="score">${v}</span></div>`).join('')}</div>`}
function analytics(){const sm={},cm={};state.rows.forEach(r=>{sm[r.Status]=(sm[r.Status]||0)+1;cm[r.Company]=(cm[r.Company]||0)+1});const dated=state.rows.filter(r=>r['Applied date']).length,ints=state.rows.filter(r=>r.Status==='Interview completed').length,rejected=state.rows.filter(r=>r.Status==='Rejected').length,closed=state.rows.filter(r=>CLOSED.has(r.Status)).map(r=>{const a=dateFrom(r['Applied date']),b=dateFrom(r['Last update']);return a&&b?Math.max(0,Math.round((b-a)/86400000)):null}).filter(x=>x!==null),avg=closed.length?Math.round(closed.reduce((a,b)=>a+b,0)/closed.length)+'d':'—',topCompanies=Object.entries(cm).sort((a,b)=>b[1]-a[1]).slice(0,10),statuses=Object.entries(sm).sort((a,b)=>b[1]-a[1]);return `${pageHead('Analytics','Descriptive application volume, status mix and organisation concentration.')}<section class="grid kpis" style="grid-template-columns:repeat(4,1fr)"><div class="card"><div class="eyebrow">Dated submissions</div><div class="kpi-value">${dated}</div></div><div class="card"><div class="eyebrow">Interviews</div><div class="kpi-value">${ints}</div></div><div class="card"><div class="eyebrow">Rejected</div><div class="kpi-value">${rejected}</div></div><div class="card"><div class="eyebrow">Avg. time to close</div><div class="kpi-value">${avg}</div></div></section><section class="grid two"><div class="card"><div class="section-title"><div><h3>Status mix</h3><p>Current record counts.</p></div></div>${bars(statuses)}</div><div class="card"><div class="section-title"><div><h3>Most targeted organisations</h3><p>Applications tracked by company.</p></div></div>${bars(topCompanies)}</div></section>`}

function quality(){
  const missingApplied=state.rows.filter(r=>r.Status!=='Prepared'&&!r['Applied date']),missingDeadline=state.rows.filter(r=>r.Status==='Prepared'&&!dateFrom(r.Deadline)),missingApply=state.rows.filter(r=>r.Status==='Prepared'&&!linkFor(r,'Apply link')),missingFolder=state.rows.filter(r=>!linkFor(r,'Application folder')),missingCv=state.rows.filter(r=>r.Status==='Prepared'&&!linkFor(r,'Tailored CV')),missingCover=state.rows.filter(r=>r.Status==='Prepared'&&!linkFor(r,'Cover letter'));
  const issues=[['Missing applied date',missingApplied],['Prepared without deadline',missingDeadline],['Prepared without apply link',missingApply],['Missing application folder',missingFolder],['Prepared without CV link',missingCv],['Prepared without cover link',missingCover]];
  const totalIssues=issues.reduce((n,x)=>n+x[1].length,0);
  return `${pageHead('Data quality','Checks the workbook you loaded. Nothing is fetched from GitHub or Google Sheets.')}<section class="grid kpis" style="grid-template-columns:repeat(3,1fr)"><div class="card"><div class="eyebrow">Records</div><div class="kpi-value">${state.rows.length}</div><div class="kpi-sub">Loaded from ${esc(state.source)}</div></div><div class="card"><div class="eyebrow">Potential issues</div><div class="kpi-value">${totalIssues}</div><div class="kpi-sub">Across six practical checks</div></div><div class="card"><div class="eyebrow">Worksheet</div><div class="kpi-value" style="font-size:1.25rem">${esc(state.sheet)}</div><div class="kpi-sub">Workbook table source</div></div></section><div class="card"><div class="section-title"><div><h3>Checks</h3><p>These are completeness flags, not automatic corrections.</p></div><button class="btn" id="qualityReload">Replace workbook</button></div><div class="data-grid">${issues.map(([label,rows])=>`<div class="data-item"><div class="v">${rows.length}</div><div class="l">${esc(label)}</div></div>`).join('')}</div>${totalIssues?`<div style="margin-top:14px">${issues.filter(x=>x[1].length).map(([label,rows])=>`<div class="section-title" style="margin-top:13px"><div><h3>${esc(label)}</h3><p>${rows.length} record${rows.length===1?'':'s'}</p></div></div>${rows.slice(0,8).map(r=>`<div class="attention-row" data-open="${r._row}"><div><strong>${esc(r.Company||'Unknown company')}</strong><div class="small">${esc(r.Role||'Unknown role')}</div></div><span class="row-chevron">›</span></div>`).join('')}`).join('')}</div>`:`<div class="notice" style="margin-top:14px">No completeness issues found by these checks.</div>`}</div>`;
}

function attachViewEvents(){
  document.querySelectorAll('[data-open]').forEach(el=>el.addEventListener('click',()=>openDrawer(+el.dataset.open)));
  document.querySelectorAll('[data-goto]').forEach(el=>el.addEventListener('click',()=>{state.view=el.dataset.goto;localStorage.setItem('jobDashView',state.view);render()}));
  const ps=document.getElementById('pipeSearch');if(ps)ps.oninput=e=>{state.filter=e.target.value;render()};
  const ph=document.getElementById('pipeHide');if(ph)ph.onchange=e=>{state.hideClosed=e.target.checked;render()};
  const s=document.getElementById('appSearch');if(s)s.oninput=e=>{state.filter=e.target.value;render()};
  const sf=document.getElementById('statusFilter');if(sf)sf.onchange=e=>{state.status=e.target.value;render()};
  const cf=document.getElementById('companyFilter');if(cf)cf.onchange=e=>{state.company=e.target.value;render()};
  const so=document.getElementById('sortFilter');if(so)so.onchange=e=>{state.sort=e.target.value;render()};
  const hc=document.getElementById('hideClosed');if(hc)hc.onchange=e=>{state.hideClosed=e.target.checked;render()};
  const csv=document.getElementById('csvBtn');if(csv)csv.onclick=exportCsv;
  const qr=document.getElementById('qualityReload');if(qr)qr.onclick=()=>document.getElementById('fileInput').click();
}

function render(){if(!state.rows.length)return;renderSidebar();const views={overview,pipeline,applications,deadlines,analytics,quality};document.getElementById('main').innerHTML=(views[state.view]||overview)();attachViewEvents()}
